redirects = []

[build]
publish = "build"
publishOrigin = "ui"
command = "npm run build"
commandOrigin = "ui"
functions = "netlify/functions"

[[redirects]]
from ="/api/"
to = "/.netlify/functions/:splat"
status=200
[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]
node_bundler="esbuild"
[functions."*"]